{{- range $name, $agent := .Values.agents }}
{{- if $agent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rootcauseway.fullname" $ }}-{{ $name }}
  labels:
    {{- include "rootcauseway.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-agent
spec:
  type: ClusterIP
  ports:
    - port: {{ $agent.port }}
      targetPort: {{ $agent.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rootcauseway.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-agent
{{- end }}
{{- end }}
