apiVersion: v1
kind: Service
metadata:
  name: {{ include "rootcauseway.fullname" . }}-frontend
  labels:
    {{- include "rootcauseway.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rootcauseway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
