apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rootcauseway.fullname" . }}-orchestrator
  labels:
    {{- include "rootcauseway.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicas }}
  selector:
    matchLabels:
      {{- include "rootcauseway.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      labels:
        {{- include "rootcauseway.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.orchestrator.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rootcauseway.fullname" . }}-config
            - secretRef:
                name: {{ include "rootcauseway.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orchestrator.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orchestrator.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
