ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS hosting_type VARCHAR(20) NOT NULL DEFAULT 'managed';
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS managed_config JSONB DEFAULT '{}';
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS llm_provider VARCHAR(20) NOT NULL DEFAULT 'platform';
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS llm_api_key_ref VARCHAR(200) DEFAULT '';
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS auto_scale BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS min_replicas INTEGER NOT NULL DEFAULT 1;
ALTER TABLE a2a_agents ADD COLUMN IF NOT EXISTS max_replicas INTEGER NOT NULL DEFAULT 3;
